package dashboardbus

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jcpaschoal/spi-exata/business/sdk/sqldb"
	"github.com/jcpaschoal/spi-exata/foundation/logger"
	"github.com/jcpaschoal/spi-exata/foundation/otel"
)

// ErrNotFound is returned when a dashboard is not found.
var ErrNotFound = errors.New("dashboard not found")

// Storer defines the behavior required by the dashboardbus to interact with the database.
type Storer interface {
	NewWithTx(tx sqldb.CommitRollbacker) (Storer, error)
	Create(ctx context.Context, d Dashboard) (Dashboard, error)
	QueryByID(ctx context.Context, dashboardID uuid.UUID) (Dashboard, error)
	Update(ctx context.Context, d Dashboard) error
}

// Core manages the set of APIs for dashboard access.
type Core struct {
	log    *logger.Logger
	storer Storer
}

// NewCore constructs a core for dashboard api access.
func NewCore(log *logger.Logger, storer Storer) *Core {
	return &Core{
		log:    log,
		storer: storer,
	}
}

// NewWithTx constructs a new Core value replacing the Storer
// value with a Storer value that is currently inside a transaction.
func (c *Core) NewWithTx(tx sqldb.CommitRollbacker) (*Core, error) {
	storer, err := c.storer.NewWithTx(tx)
	if err != nil {
		return nil, fmt.Errorf("newWithTx: %w", err)
	}

	return NewCore(c.log, storer), nil
}

// Create adds a new dashboard to the system.
func (c *Core) Create(ctx context.Context, nd NewDashboard) (Dashboard, error) {
	ctx, span := otel.AddSpan(ctx, "business.dashboardbus.create")
	defer span.End()

	now := time.Now()

	// ID is generated by the database/resource insertion logic,
	// but we construct the struct here. The Storer will handle the ID assignment via RETURNING or logic.
	// However, usually we generate UUIDs in code if using uuidv7, but here Dashboard ID depends on Resource ID.
	// We will let the Storer populate the ID.

	d := Dashboard{
		TenantID:  nd.TenantID,
		Name:      nd.Name,
		Domain:    nd.Domain,
		Logo:      nd.Logo,
		CreatedAt: now,
		UpdatedAt: now,
	}

	d, err := c.storer.Create(ctx, d)
	if err != nil {
		return Dashboard{}, fmt.Errorf("create: %w", err)
	}

	return d, nil
}

// QueryByID finds the dashboard by the specified ID.
func (c *Core) QueryByID(ctx context.Context, dashboardID uuid.UUID) (Dashboard, error) {
	ctx, span := otel.AddSpan(ctx, "business.dashboardbus.queryByID")
	defer span.End()

	dashboard, err := c.storer.QueryByID(ctx, dashboardID)
	if err != nil {
		return Dashboard{}, fmt.Errorf("query: dashboardID[%s]: %w", dashboardID, err)
	}

	return dashboard, nil
}

// Update modifies data about a dashboard.
func (c *Core) Update(ctx context.Context, d Dashboard, ud UpdateDashboard) (Dashboard, error) {
	ctx, span := otel.AddSpan(ctx, "business.dashboardbus.update")
	defer span.End()

	if ud.Name != nil {
		d.Name = *ud.Name
	}

	if ud.Domain != nil {
		d.Domain = ud.Domain
	}

	if ud.Logo != nil {
		d.Logo = ud.Logo
	}

	d.UpdatedAt = time.Now()

	if err := c.storer.Update(ctx, d); err != nil {
		return Dashboard{}, fmt.Errorf("update: %w", err)
	}

	return d, nil
}
